# Generated by Django 4.1.4 on 2022-12-13 10:17

import api.v1.accounts.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('object', api.v1.accounts.models.CustomUserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
